# Generated by Django 3.0.7 on 2020-06-16 20:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='theoryTag.Chapter')),
            ],
            options={
                'unique_together': {('name', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='SubConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subConcepts', to='theoryTag.Concept')),
            ],
            options={
                'unique_together': {('name', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('theory', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleQues1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleSol1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleQues2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleSol2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleQues3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleSol3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleQues4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleSol4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleQues5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleSol5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleQues6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleSol6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleQues7', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyExampleSol7', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleQues1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleSol1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleQues2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleSol2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleQues3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleSol3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleQues4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleSol4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleQues5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleSol5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleQues6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleSol6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleQues7', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumExampleSol7', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleQues1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleSol1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleQues2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleSol2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleQues3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleSol3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleQues4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleSol4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleQues5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleSol5', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleQues6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardExampleSol6', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyIntegerTypeQues1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyIntegerTypeSol1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyIntegerTypeQues2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('easyIntegerTypeSol2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumIntegerTypeQues1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumIntegerTypeSol1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumIntegerTypeQues2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mediumIntegerTypeSol2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardIntegerTypeQues1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('hardIntegerTypeSol1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('importance', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('duration', models.IntegerField()),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mnemonics', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('videoUrl', models.URLField()),
                ('targetExam', models.CharField(choices=[('IIT', 'IIT'), ('NEET', 'NEET')], max_length=100)),
                ('wowTheory', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('wowQues', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('wowReason', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisiteOf', to='theoryTag.SubConcept')),
                ('subConcept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Theory', to='theoryTag.SubConcept')),
                ('twinConcepts', models.ManyToManyField(blank=True, related_name='twinConceptOf', to='theoryTag.SubConcept')),
            ],
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ans', ckeditor_uploader.fields.RichTextUploadingField()),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('tricky', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=100)),
                ('rated', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ques', to='theoryTag.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='theoryTag.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('name', 'subject')},
        ),
    ]
