# Generated by Django 3.0.7 on 2020-06-17 06:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theoryTag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('question_no', models.IntegerField(blank=True, null=True)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('subconcepts', models.ManyToManyField(blank=True, related_name='subconceptsof', to='theoryTag.SubConcept')),
            ],
            options={
                'unique_together': {('userId', 'question_no')},
            },
        ),
    ]
