# Generated by Django 3.0.7 on 2020-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theoryTag', '0002_crossconcept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='tricky',
        ),
        migrations.AddField(
            model_name='ques',
            name='subConcept',
            field=models.ManyToManyField(blank=True, related_name='questions', to='theoryTag.SubConcept'),
        ),
    ]
