# Generated by Django 3.0.7 on 2020-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theoryTag', '0003_auto_20200617_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='error',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30),
        ),
    ]
