# Generated by Django 3.0.7 on 2020-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theoryTag', '0005_auto_20200621_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
